src/models/order.py
from src.models.melhor_envio import ShippingTag
from src.models.woo_api import getProductInfo
from src.models.trello import TrelloCard
from datetime import datetime
import json
import re


class Order:
    def __init__(self, client_first_name, client_last_name, cpf, client_address_1, number, complement, neighbor, city, state, cep, phone, shipping_type, shipping_price, products_info, total_value, forma_pgto, trello_list):
        self.client_first_name = client_first_name
        self.client_last_name = client_last_name
        self.cpf = cpf
        self.client_address_1 = client_address_1
        self.number = number
        self.complement = complement
        self.neighbor = neighbor
        self.city = city
        self.state = state
        self.cep = cep
        self.phone = phone
        self.shipping_type = shipping_type
        self.shipping_price = shipping_price
        self.products_info = products_info
        self.products_details = {
            "declaration_info": [],
            "imgs_urls_list": []
        }
        self.total_value = total_value
        self.forma_pgto = forma_pgto
        self.trello_list = trello_list

        phoneOnlyNumbers = re.sub(r'[^0-9]', '', self.phone)
        self.linkzap = f'https://api.whatsapp.com/send?phone=55{phoneOnlyNumbers}'
        self.date_start = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')

    def get_trello_card_desc(self):
        return f'Nome : {self.client_first_name} {self.client_last_name}\nRua/Avenida : {self.client_address_1}\nNúmero: {self.number}\nComplemento: {self.complement}\nBairro: {self.neighbor}\nCidade: {self.city}\nEstado: {self.state}\nCep: {self.cep}\n\n------------------------\n\nCPF: {self.cpf}\nLink para o WhatsApp: \n{self.linkzap}'

    def get_trello_card_name(self):
        return f"{self.client_first_name} {self.client_last_name}"

    def to_json(self):
        return json.dumps(self, default=lambda o: o.__dict__, indent=4)

    def create_trello_card(self):
        card_name = self.get_trello_card_name()
        desc = self.get_trello_card_desc()
        card_labels_ids = None
        list_id = self.trello_list

        trello_card = TrelloCard(
            card_name, desc, list_id, card_labels_ids, self.products_info)

        card_info = trello_card.create()
        return card_info

    def create_shipping_tag(self):
        shipping_tag = ShippingTag(f"{self.client_first_name} {self.client_last_name}", self.cpf, self.client_address_1, self.complement, self.number, self.neighbor,
                                   self.city, self.state, self.cep, self.products_details['declaration_info'], self.shipping_price, self.shipping_type, None)
        shipping_tag.send_to_cart()
        return


class OrderAddressForm(Order):
    def __init__(self, form_data):
        client_first_name = form_data['info']['name_1']
        client_last_name = form_data['info']['name_2']
        cpf = form_data['info']['cpf']
        client_address_1 = form_data['info']['address_1']
        number = form_data['info']['address_number']
        complement = form_data['info']['complemento']
        neighbor = form_data['info']['bairro']
        city = form_data['info']['cidade']
        state = form_data['info']['estado']
        cep = form_data['info']['cep']
        phone = form_data['info']['zap']
        shipping_type = form_data['tipo_frete']
        shipping_price = form_data['preco_frete']
        products_info = form_data['produtos']
        forma_pgto = form_data['forma_pgto']
        total_value = None
        trello_list = "6315059660711c0109c21c09"

        super().__init__(client_first_name, client_last_name, cpf,
                         client_address_1, number, complement, neighbor, city, state, cep, phone, shipping_type, shipping_price, products_info, total_value, forma_pgto, trello_list)
        self.id = None

    def turn_codes_str_into_int_list(self):
        products_codes_in_list = re.findall(r"\d{4}", self.products_info)
        return [int(i) for i in products_codes_in_list]

    def get_products_details(self):
        if self.products_info == None:
            print('Não há códigos de roupas para anexar ao cartão!')
            return None

        codes_int_list = self.turn_codes_str_into_int_list()

        for code in codes_int_list:
            prodinfo = getProductInfo(code)

            if prodinfo == None:
                return None

            imgs_src = prodinfo['images'][0]['src']
            product_name = prodinfo['name']
            product_price = prodinfo['price']

            info_for_declaration = {
                "name": product_name,
                "quantity": 1,
                "unitary_value": product_price
            }

            self.products_details['imgs_urls_list'].append(imgs_src)
            self.products_details['declaration_info'].append(
                info_for_declaration)

    def create_trello_card(self):
        card_info = super().create_trello_card()
        self.get_products_details()

        return TrelloCard.set_attachs(
            card_info['id'], self.products_details['imgs_urls_list'])


class OrderSite(Order):
    def __init__(self, order_data):
        client_first_name = order_data['shipping']['first_name']
        client_last_name = order_data['shipping']['last_name']
        cpf = order_data['billing']['cpf']
        client_address_1 = order_data['shipping']['address_1']
        number = order_data['shipping']['number']
        complement = order_data['shipping']['address_2']
        neighbor = order_data['shipping']['neighborhood']
        city = order_data['shipping']['city']
        state = order_data['shipping']['state']
        cep = order_data['shipping']['postcode']
        phone = order_data['billing']['phone']
        shipping_type = order_data['shipping_lines'][0]['method_id']
        shipping_price = order_data['shipping_lines'][0]['total']
        products_info = order_data['line_items']
        total_value = order_data['total']
        forma_pgto = order_data['payment_method_title']
        trello_list = '63191b83a8e4af048326a8b2'

        super().__init__(client_first_name, client_last_name, cpf,
                         client_address_1, number, complement, neighbor, city, state, cep, phone, shipping_type, shipping_price, products_info, total_value, forma_pgto, trello_list)

        self.id = order_data['id']

    def get_products_details(self):
        if not self.products_info:
            print('Não há códigos de roupas para anexar ao cartão!')
            return None

        for product in self.products_info:
            img_url = product['image']['src']
            name = product['name']
            quantity = product['quantity']
            price = product['subtotal']

            info_for_declaration = {
                "name": name,
                "quantity": quantity,
                "unitary_value": price
            }

            self.products_details['imgs_urls_list'].append(img_url)
            self.products_details['declaration_info'].append(
                info_for_declaration)

            print(self.products_details)

    def create_trello_card(self):
        card_info = super().create_trello_card()
        self.get_products_details()

        TrelloCard.set_attachs(
            card_info['id'], self.products_details['imgs_urls_list'])
        return


class AdressFormLink():
    def __init__(self, link_data):
        self.cod_produtos = link_data['cod_produtos']
        self.preco_frete = link_data['preco_frete']
        self.tipo_frete = link_data['tipo_frete']
        self.forma_pgto = link_data['forma_pgto']
        self.link = None

    def to_json(self):
        return json.dumps(self, default=lambda o: o.__dict__, indent=3)

    def create(self):
        link = 'https://anaramosmoda.com/formulario-de-pedido?'

        if self.cod_produtos:
            link = f"{link}produtos={self.cod_produtos}&"

        if self.preco_frete:
            link = f"{link}preco_frete={self.preco_frete}&"

        self.link = link

src/controllers/orders_controller.py
from flask import render_template, make_response
from src.models.order import OrderSite, OrderAddressForm, AdressFormLink
from src.utils.variables import ORDER_SAMPLE


def address_form(form_data):
    address_form = OrderAddressForm(form_data)
    address_form.create_trello_card()
    address_form.create_shipping_tag()
    return make_response(render_template("order-form_confirmation.html"), 200)


def new_order_site(order_info):
    if not order_info:
        order_info = ORDER_SAMPLE

    new_order = OrderSite(order_info)
    new_order.create_trello_card()
    new_order.create_shipping_tag()


def criar_link_form(link_data):
    address_form_link = AdressFormLink(link_data)
    address_form_link.create()
    return make_response(render_template("order-form-create-link_confirmation.html", link_form=address_form_link.link), 200)

src/routes.py
from flask import request, Blueprint
from flask.wrappers import Response
from src.controllers import views_controller
from src.controllers import orders_controller

main = Blueprint('main', __name__)


@main.route('/', methods=['GET'])
def show_home():
    return views_controller.home()


@main.route('/formulario-de-pedido', methods=['GET'])
def order_form_page():
    return views_controller.order_form()


@main.route('/criar-link-formulario', methods=['GET', 'POST'])
def create_form_link():
    if request.method == 'GET':
        return views_controller.criar_link_form()

    data = {
        "cod_produtos": request.form.get('cod_produtos'),
        "preco_frete": request.form.get('preco_frete'),
        "tipo_frete": request.form.get('tipo_frete'),
        "forma_pgto": request.form.get('forma_pgto'),
    }
    return orders_controller.criar_link_form(data)


@main.route('/address-form', methods=['POST'])
def address_form():
    data = {
        "forma_pgto": request.form.get('forma_pgto'),
        "produtos": request.form.get('produtos'),
        "tipo_frete": request.form.get('tipo_frete'),
        "preco_frete": request.form.get('preco_frete'),
        "info": request.form.to_dict()
    }

    return orders_controller.address_form(data)


@main.route('/new_order', methods=['POST'])
def new_order_site():
    order_info = request.get_json(silent=True, force=True)
    orders_controller.new_order_site(order_info)

    return Response(status=201)

src/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/styles.css')}}" />
    <title>Formulário de Pedido - Ana Ramos Moda</title>
  </head>
  <body>
    <h1>Hello World</h1>
  </body>
</html>

src/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hello World Login</title>
  </head>
  <body>
    <form action="/login" method="post">
      <input type="username" name="username" id="user_form" placeholder="Username" />
      <input type="password" name="password" id="user_pass" placeholder="Password" />
      <input type="submit" value="Log in" />
    </form>
  </body>
</html>

src/templates/order-form-create-link.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/styles.css')}}" />
    <title>Criar link de Formulário - Ana Ramos Moda</title>
  </head>
  <body>
    <!-- multistep form -->
    <form id="msform" action="{{ url_for('main.create_form_link') }}" method="POST">
      <fieldset>
        <h2 class="fs-title">Criação de Links de Formulários</h2>
        <h3 class="fs-subtitle">
          Preencha as Informações sobre o pedido para criar um link e enviar para a
          cliente
        </h3>
        <label for="cod_produtos">Digite os códigos dos produtos</label>
        <input
          placeholder="Ex: 3282 ou 4001,3226"
          name="cod_produtos"
          type="text"
          pattern="([aA-zZáéíóúÁÉÍÓÚ 0-9]+)"
          title="Para mais produtos separe por virgulas sem espaço"
        />
        <label for="preco_frete">Qual o valor do frete?</label>
        <input
          placeholder="Sem centavos: Ex 25 ou 15 ou 0"
          name="preco_frete"
          type="number"
          title="Somente 2 dígitos"
          pattern="([0-9][0-9]])"
        />

        <label for="tipo_frete">PAC ou SEDEX?</label>
        <select name="tipo_frete" id="">
          <option value="PAC">PAC</option>
          <option value="SEDEX">SEDEX</option>
        </select>

        <label for="forma_pgto">PIX ou Link MP?</label>
        <select name="forma_pgto" id="">
          <option value="PIX">PIX</option>
          <option value="Link MP">Link MP</option>
        </select>
        <input type="submit" name="enviar" class="submit action-button" value="Enviar" />
        <h3 class="fs-subtitle">
          Após enviar, por favor aguarde alguns segundo para receber a confirmação
        </h3>
      </fieldset>
    </form>
  </body>
</html>

src/templates/order-form-create-link_confirmation.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/styles.css')}}" />
    <title>Criação de Links - Ana Ramos Moda</title>
  </head>
  <body>
    <!-- multistep form -->
    <form id="msform" action="{{ url_for('main.address_form') }}" method="POST">
      <fieldset>
        <h2 class="fs-title">Link criado</h2>
        <h3 class="fs-subtitle">Copie o link abaixo</h3>
        <a href="{{ link_form }}">{{ link_form }}</a>
      </fieldset>
    </form>
  </body>
</html>

src/templates/order-form.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/styles.css')}}" />
    <title>Formulário de Pedido - Ana Ramos Moda</title>
  </head>
  <body>
    <!-- multistep form -->
    <form id="msform" action="{{ url_for('main.address_form') }}" method="POST">
      <fieldset>
        <h2 class="fs-title">Endereço de entrega</h2>
        <h3 class="fs-subtitle">
          Por favor, preecha o endereço onde deseja receber seus produtos.
        </h3>
        <input
          placeholder="Primeiro Nome"
          name="name_1"
          type="text"
          pattern="([aA-zZáéíóúÁÉÍÓÚ 0-9]+)"
          title="Apenas letras. Até 20 letras"
          maxlength="20"
          required
        />
        <input
          placeholder="Sobrenome"
          name="name_2"
          type="text"
          pattern="([aA-zZáéíóúÁÉÍÓÚãÃõÕ 0-9]+)"
          title="Apenas letras. Até 20 letras"
          maxlength="20"
          required
        />
        <input
          type="number"
          name="cep"
          placeholder="CEP"
          title="Apenas números. Inclua os zeros. Ex: 09172180"
          maxlength="8"
          minlength="8"
          id="cep"
          required
        />
        <input
          placeholder="Logradouro"
          name="address_1"
          type="text"
          pattern="([aA-zZáéíóúÁÉÍÓÚãÃõÕ 0-9]+)"
          title="Apenas letras. Até 40 letras"
          maxlength="40"
          id="address_1"
          required
        />

        <input
          placeholder="Número"
          name="address_number"
          type="text"
          title="Apenas letras e números. Até 12 dígitos"
          pattern="([aA-zZáéíóúÁÉÍÓÚãÃõÕ 0-9]+)"
          maxlength="12"
          required
        />
        <input
          placeholder="Bairro"
          name="bairro"
          type="text"
          title="Até 24 caracteres"
          maxlength="24"
          required
          pattern="([aA-zZáéíóúÁÉÍÓÚãÃõÕ 0-9]+)"
          id="bairro"
        />

        <input
          placeholder="Cidade"
          name="cidade"
          type="text"
          title="Até 40 caracteres"
          maxlength="40"
          required
          id="cidade"
          pattern="([aA-zZáéíóúÁÉÍÓÚãÃõÕ 0-9]+)"
        />
        <input
          placeholder="Bloco / Ap / Casa"
          name="complemento"
          type="text"
          title="Até 24 caracteres"
          maxlength="24"
          pattern="([aA-zZáéíóúÁÉÍÓÚãÃõÕ 0-9]+)"
        />
        <input
          placeholder="Informações adicionais"
          name="obs"
          type="text"
          title="Até 30 caracteres"
          maxlength="30"
          pattern="([aA-zZáéíóúÁÉÍÓÚãÃõÕ 0-9]+)"
        />
        <select name="estado" id="estado" required>
          <option value="AC">AC</option>
          <option value="AL">AL</option>
          <option value="AP">AP</option>
          <option value="AM">AM</option>
          <option value="BA">BA</option>
          <option value="CE">CE</option>
          <option value="DF">DF</option>
          <option value="ES">ES</option>
          <option value="GO">GO</option>
          <option value="MA">MA</option>
          <option value="MT">MT</option>
          <option value="MS">MS</option>
          <option value="MG">MG</option>
          <option value="PA">PA</option>
          <option value="PB">PB</option>
          <option value="PR">PR</option>
          <option value="PE">PE</option>
          <option value="PI">PI</option>
          <option value="RJ">RJ</option>
          <option value="RN">RN</option>
          <option value="RS">RS</option>
          <option value="RO">RO</option>
          <option value="RR">RR</option>
          <option value="SC">SC</option>
          <option value="SP">SP</option>
          <option value="SE">SE</option>
          <option value="TO">TO</option>
        </select>
        <input
          placeholder="CPF para os Correios"
          name="cpf"
          type="text"
          pattern="(\d{3}\.?\d{3}\.?\d{3}-?\d{2})|(\d{2}\.?\d{3}\.?\d{3}/?\d{4}-?\d{2})"
          title="Apenas Números. 11 Dígitos. Inclua os zeros. Ex: 00652158925"
          maxlength="11"
          minlength="11"
          required
        />
        <input
          placeholder="WhatsApp (DDD + Telefone)"
          type="number"
          name="zap"
          title="Apenas números. Ex: 11982942057"
          maxlength="11"
          minlength="10"
          required
        />

        <input
          placeholder="Email (Código de rastreamento)"
          name="email"
          type="email"
          title="Formato com @ .com .com.br"
        />
        <input placeholder="Produtos" name="produtos" type="hidden" id="produtos" />
        <input placeholder="Tipo frete" name="tipo_frete" type="hidden" id="tipo_frete" />
        <input placeholder="Forma pgto" name="forma_pgto" type="hidden" id="forma_pgto" />
        <input
          placeholder="Preco frete"
          name="preco_frete"
          type="hidden"
          id="preco_frete"
        />
        <input type="submit" name="enviar" class="submit action-button" value="Enviar" />
        <h3 class="fs-subtitle">
          Após enviar, por favor aguarde alguns segundo para receber a confirmação
        </h3>
      </fieldset>
    </form>
    <script
      src="https://code.jquery.com/jquery-3.6.3.min.js"
      integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
      crossorigin="anonymous"
    ></script>
    <script src="{{ url_for('static' , filename='js/form_autocomplete.js')}}"></script>
  </body>
</html>

src/templates/order-form_confirmation.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/styles.css')}}" />
    <title>Formulário de Pedido - Ana Ramos Moda</title>
  </head>
  <body>
    <!-- multistep form -->
    <form id="msform" action="{{ url_for('main.address_form') }}" method="POST">
      <fieldset>
        <h2 class="fs-title">Parabéns. Recebemos seu endereço</h2>
        <h3 class="fs-subtitle">
          Vamos iniciar seu pedido e separar seu look antes que acabe!
        </h3>
        <h3 class="fs-subtitle">Você pode fechar essa pagina tranquilamente</h3>
      </fieldset>
    </form>
  </body>
</html>